# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Sercan/PycharmProjects/Eski Projeler/tab ama pyqt5/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(532, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tak_Cik = QtWidgets.QPushButton(self.centralwidget)
        self.Tak_Cik.setGeometry(QtCore.QRect(10, 60, 159, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Tak_Cik.setFont(font)
        self.Tak_Cik.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Tak_Cik.setIconSize(QtCore.QSize(40, 40))
        self.Tak_Cik.setObjectName("Tak_Cik")
        self.Tak_Ekle_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Tak_Ekle_3.setGeometry(QtCore.QRect(9, 9, 143, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Tak_Ekle_3.setFont(font)
        self.Tak_Ekle_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Tak_Ekle_3.setIconSize(QtCore.QSize(40, 40))
        self.Tak_Ekle_3.setObjectName("Tak_Ekle_3")
        self.Sonuc = QtWidgets.QPushButton(self.centralwidget)
        self.Sonuc.setGeometry(QtCore.QRect(10, 180, 127, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Sonuc.setFont(font)
        self.Sonuc.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Sonuc.setIconSize(QtCore.QSize(40, 40))
        self.Sonuc.setObjectName("Sonuc")
        self.Baslat = QtWidgets.QPushButton(self.centralwidget)
        self.Baslat.setGeometry(QtCore.QRect(10, 130, 193, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Baslat.setFont(font)
        self.Baslat.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Baslat.setIconSize(QtCore.QSize(40, 40))
        self.Baslat.setObjectName("Baslat")
        self.Break = QtWidgets.QPushButton(self.centralwidget)
        self.Break.setGeometry(QtCore.QRect(290, 590, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Break.setFont(font)
        self.Break.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Break.setIconSize(QtCore.QSize(40, 40))
        self.Break.setObjectName("Break")
        self.Konu_Gos = QtWidgets.QPushButton(self.centralwidget)
        self.Konu_Gos.setGeometry(QtCore.QRect(10, 230, 161, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Konu_Gos.setFont(font)
        self.Konu_Gos.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Konu_Gos.setIconSize(QtCore.QSize(40, 40))
        self.Konu_Gos.setObjectName("Konu_Gos")
        self.Takim_Gor = QtWidgets.QPushButton(self.centralwidget)
        self.Takim_Gor.setGeometry(QtCore.QRect(10, 290, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Takim_Gor.setFont(font)
        self.Takim_Gor.setObjectName("Takim_Gor")
        self.Juri = QtWidgets.QPushButton(self.centralwidget)
        self.Juri.setGeometry(QtCore.QRect(10, 370, 127, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Juri.setFont(font)
        self.Juri.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Juri.setIconSize(QtCore.QSize(40, 40))
        self.Juri.setObjectName("Juri")
        self.Salon = QtWidgets.QPushButton(self.centralwidget)
        self.Salon.setGeometry(QtCore.QRect(10, 420, 141, 39))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Salon.setFont(font)
        self.Salon.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Salon.setIconSize(QtCore.QSize(40, 40))
        self.Salon.setObjectName("Salon")
        self.Yoklama = QtWidgets.QPushButton(self.centralwidget)
        self.Yoklama.setGeometry(QtCore.QRect(10, 480, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Yoklama.setFont(font)
        self.Yoklama.setObjectName("Yoklama")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ana Menü"))
        self.Tak_Cik.setText(_translate("MainWindow", "Takım Çıkar"))
        self.Tak_Ekle_3.setText(_translate("MainWindow", "Takım Ekle"))
        self.Sonuc.setText(_translate("MainWindow", "Sonuç Gir"))
        self.Baslat.setText(_translate("MainWindow", "Maça Başlangıç"))
        self.Break.setText(_translate("MainWindow", "Break"))
        self.Konu_Gos.setText(_translate("MainWindow", "Konu Göster"))
        self.Takim_Gor.setText(_translate("MainWindow", "Takımları Gör"))
        self.Juri.setText(_translate("MainWindow", "Juri Ekle"))
        self.Salon.setText(_translate("MainWindow", "Salon Ekle"))
        self.Yoklama.setText(_translate("MainWindow", "Yoklama"))

