# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Sercan/PycharmProjects/Eski Projeler/tab ama pyqt5/sonuc_gir.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(975, 527)
        self.Salon = QtWidgets.QComboBox(Form)
        self.Salon.setGeometry(QtCore.QRect(680, 40, 191, 51))
        self.Salon.setObjectName("Salon")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(490, 50, 155, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Kaydet = QtWidgets.QPushButton(Form)
        self.Kaydet.setGeometry(QtCore.QRect(790, 440, 171, 71))
        self.Kaydet.setObjectName("Kaydet")
        self.HA = QtWidgets.QLabel(Form)
        self.HA.setGeometry(QtCore.QRect(20, 140, 155, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.HA.setFont(font)
        self.HA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HA.setText("")
        self.HA.setWordWrap(True)
        self.HA.setObjectName("HA")
        self.MA = QtWidgets.QLabel(Form)
        self.MA.setGeometry(QtCore.QRect(250, 140, 155, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.MA.setFont(font)
        self.MA.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MA.setText("")
        self.MA.setWordWrap(True)
        self.MA.setObjectName("MA")
        self.MK = QtWidgets.QLabel(Form)
        self.MK.setGeometry(QtCore.QRect(720, 140, 155, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.MK.setFont(font)
        self.MK.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MK.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MK.setText("")
        self.MK.setWordWrap(True)
        self.MK.setObjectName("MK")
        self.HK = QtWidgets.QLabel(Form)
        self.HK.setGeometry(QtCore.QRect(480, 140, 155, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.HK.setFont(font)
        self.HK.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HK.setText("")
        self.HK.setWordWrap(True)
        self.HK.setObjectName("HK")
        self.HA1P = QtWidgets.QLineEdit(Form)
        self.HA1P.setGeometry(QtCore.QRect(180, 210, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.HA1P.setFont(font)
        self.HA1P.setText("")
        self.HA1P.setObjectName("HA1P")
        self.HA2P = QtWidgets.QLineEdit(Form)
        self.HA2P.setGeometry(QtCore.QRect(180, 280, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.HA2P.setFont(font)
        self.HA2P.setText("")
        self.HA2P.setObjectName("HA2P")
        self.MA1P = QtWidgets.QLineEdit(Form)
        self.MA1P.setGeometry(QtCore.QRect(410, 210, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.MA1P.setFont(font)
        self.MA1P.setText("")
        self.MA1P.setObjectName("MA1P")
        self.MA2P = QtWidgets.QLineEdit(Form)
        self.MA2P.setGeometry(QtCore.QRect(410, 280, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.MA2P.setFont(font)
        self.MA2P.setText("")
        self.MA2P.setObjectName("MA2P")
        self.HK1P = QtWidgets.QLineEdit(Form)
        self.HK1P.setGeometry(QtCore.QRect(650, 220, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.HK1P.setFont(font)
        self.HK1P.setText("")
        self.HK1P.setObjectName("HK1P")
        self.HK2P = QtWidgets.QLineEdit(Form)
        self.HK2P.setGeometry(QtCore.QRect(650, 280, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.HK2P.setFont(font)
        self.HK2P.setText("")
        self.HK2P.setObjectName("HK2P")
        self.MK1P = QtWidgets.QLineEdit(Form)
        self.MK1P.setGeometry(QtCore.QRect(880, 220, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.MK1P.setFont(font)
        self.MK1P.setText("")
        self.MK1P.setObjectName("MK1P")
        self.MK2P = QtWidgets.QLineEdit(Form)
        self.MK2P.setGeometry(QtCore.QRect(880, 280, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.MK2P.setFont(font)
        self.MK2P.setText("")
        self.MK2P.setObjectName("MK2P")
        self.HAP = QtWidgets.QLineEdit(Form)
        self.HAP.setGeometry(QtCore.QRect(50, 350, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.HAP.setFont(font)
        self.HAP.setText("")
        self.HAP.setObjectName("HAP")
        self.MAP = QtWidgets.QLineEdit(Form)
        self.MAP.setGeometry(QtCore.QRect(270, 350, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.MAP.setFont(font)
        self.MAP.setText("")
        self.MAP.setObjectName("MAP")
        self.HKP = QtWidgets.QLineEdit(Form)
        self.HKP.setGeometry(QtCore.QRect(500, 350, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.HKP.setFont(font)
        self.HKP.setText("")
        self.HKP.setObjectName("HKP")
        self.MKP = QtWidgets.QLineEdit(Form)
        self.MKP.setGeometry(QtCore.QRect(740, 350, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.MKP.setFont(font)
        self.MKP.setText("")
        self.MKP.setObjectName("MKP")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 155, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Salon_2 = QtWidgets.QComboBox(Form)
        self.Salon_2.setGeometry(QtCore.QRect(180, 40, 191, 51))
        self.Salon_2.setObjectName("Salon_2")
        self.HA1 = QtWidgets.QComboBox(Form)
        self.HA1.setGeometry(QtCore.QRect(20, 210, 141, 41))
        self.HA1.setObjectName("HA1")
        self.HA2 = QtWidgets.QComboBox(Form)
        self.HA2.setGeometry(QtCore.QRect(20, 280, 141, 41))
        self.HA2.setObjectName("HA2")
        self.MA1 = QtWidgets.QComboBox(Form)
        self.MA1.setGeometry(QtCore.QRect(250, 210, 141, 41))
        self.MA1.setObjectName("MA1")
        self.MA2 = QtWidgets.QComboBox(Form)
        self.MA2.setGeometry(QtCore.QRect(250, 280, 141, 41))
        self.MA2.setObjectName("MA2")
        self.HK1 = QtWidgets.QComboBox(Form)
        self.HK1.setGeometry(QtCore.QRect(480, 210, 141, 41))
        self.HK1.setObjectName("HK1")
        self.HK2 = QtWidgets.QComboBox(Form)
        self.HK2.setGeometry(QtCore.QRect(480, 280, 141, 41))
        self.HK2.setObjectName("HK2")
        self.MK1 = QtWidgets.QComboBox(Form)
        self.MK1.setGeometry(QtCore.QRect(720, 220, 141, 41))
        self.MK1.setObjectName("MK1")
        self.MK2 = QtWidgets.QComboBox(Form)
        self.MK2.setGeometry(QtCore.QRect(720, 280, 141, 41))
        self.MK2.setObjectName("MK2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Salon Seçiniz:"))
        self.Kaydet.setText(_translate("Form", "Kaydet"))
        self.label_2.setText(_translate("Form", "Tur Seçiniz:"))

